### ISSUE TITLE
Logo Position

### ISSUE THREAD

**Issue by jhemmmm** [tapioca24/videojs-logo#15]
The logo position isn't working on my side.

**Comment by EbubekirUstalar** [comment]
You just need to add the following CSS rule;

.vjs-logo-content{
  position: absolute;
}

**Comment by mitani24** [comment]
@jhemmmm 
Thanks for your report and sorry for the late reply.
Did you solve the issue?

Please make sure that `node_modules/videojs-logo/dist/videojs-logo.css` is imported.
If that doesn't help, can you provide a minimum environment to reproduce it?

**Comment by tapioca24** [comment]
@jhemmmm 
Thanks for your report and sorry for the late reply.
Did you solve the issue?

Please make sure that `node_modules/videojs-logo/dist/videojs-logo.css` is imported.
If that doesn't help, can you provide a minimum environment to reproduce it?

**Comment by jhemmmm** [comment]
I'm not sure what I did, I fixed it on my own.
