### ISSUE TITLE
How to add opacity to the logo

### ISSUE THREAD

**Issue by nwaughachukwuma** [tapioca24/videojs-logo#2]
@tapioca24 is it possible to add opacity to the logo item? It would be nice if you exposed an opacity prop on the component. Please let me know if it's in your plans and if you'll accept a PR with this proposal

Thanks

**Comment by tapioca24** [comment]
@nwaughachukwuma 
Thanks for your suggestion!
You can add opacity by overriding the CSS. An example is shown below.

```css
.video-js.vjs-logo .vjs-logo-content {
    opacity: 0.5;
}
```

I considered exposing the opacity prop on the component, but feared a loss of customizability, so I decided against it. If you have a good idea of how to solve this, I welcome it.

**Comment by nwaughachukwuma** [comment]
@tapioca24, thanks for pointing me in the right direction. I'll look at making a PR for this when I have the time.

**Comment by nwaughachukwuma** [comment]
@tapioca24 for quick feedback before I go too far, I have added a new option for opacity with a default of 1, then in `_setup()` method I have done the following:

```javascript
 // Create img element
 const img = document.createElement('img'); // eslint-disable-line no-undef

 img.src = this.options.image;

 const { width, height, opacity } = this.options; // <-- notice the opacity attr

 if (width) {
   img.width = width;
 }
 if (height) {
   img.height = height;
 }
 // this is new
 if (opacity) {
   img.style.opacity = opacity
 }
```
Please see this [Pen](https://codepen.io/nwaughachukwuma-the-decoder/pen/mdeMrEw?editors=1010) to see it works

**Comment by tapioca24** [comment]
@nwaughachukwuma LGTM👍
