### ISSUE TITLE
resize logo

### ISSUE THREAD

**Issue by kroerig** [tapioca24/videojs-logo#20]
Hello,

how can I achieve that the logo resizes on mobile devices?

eg. I define

```
                 width: '80',
                 height: '80',

```
i looks fine on desktops but on in fullscreen mode on mobile devices the logo is too big.

Thx.

**Comment by mitani24** [comment]
Hi @kroerig
Can you provide some sample code to reproduce it?

**Comment by tapioca24** [comment]
Hi @kroerig
Can you provide some sample code to reproduce it?

**Comment by kroerig** [comment]
Have a look here: https://stream.leibniz-remscheid.de/

There is actually now video stream, but the logo.

**Comment by tapioca24** [comment]
I tried to access it on my mobile device and it seems to work fine.

![screenshot](https://user-images.githubusercontent.com/12683107/122965284-fc016c80-d3c2-11eb-9c71-bb4e7e124bb4.png)

**Comment by kroerig** [comment]
so, here's the problem again.
https://www.leibniz-remscheid.de/test/

the logo is too much inside the video. When enabling fullscreen it is ok.
