### ISSUE TITLE
live graphics overlay

### ISSUE THREAD

**Issue by stephanschulz** [tapioca24/videojs-logo#9]
i was wondering if your plugin can be used to overlay any live graphic on top of the video player?

right now i am generating a audio wave lines inside a canvas element. this gets automatically drawn beside the video because it's in a different <div>. 
but i would like it to be right over the video.

would your plugin be the right choice for this?

**Comment by tapioca24** [comment]
Hi @stephanschulz 
Sorry, this plugin is implemented using the img element, so you can't overlay the canvas element.
